-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."role" add column "parentLink" boolean
--  not null default 'false';
