-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO  "public"."subscription_plan_type" (value) VALUES ('STARTUP');
-- INSERT INTO  "public"."subscription_plan_type" (value) VALUES ('BUSINESS');
