[build]
  command = "npm ci && npx turbo build && cd website && npm install && npm run build && cd .. && mkdir -p dist && cp -r packages/webapp/dist/* dist/ && cp -r website/dist/* dist/ && cat packages/webapp/dist/_redirects >> dist/_redirects"
  publish = "dist"
