table:
  name: circle
  schema: public
object_relationships:
  - name: org
    using:
      foreign_key_constraint_on: orgId
  - name: parent
    using:
      foreign_key_constraint_on: parentId
  - name: role
    using:
      foreign_key_constraint_on: roleId
array_relationships:
  - name: children
    using:
      foreign_key_constraint_on:
        column: parentId
        table:
          name: circle
          schema: public
  - name: hostCircleLinks
    using:
      foreign_key_constraint_on:
        column: circleId
        table:
          name: circle_link
          schema: public
  - name: invitedCircleLinks
    using:
      foreign_key_constraint_on:
        column: parentId
        table:
          name: circle_link
          schema: public
  - name: leaders
    using:
      manual_configuration:
        column_mapping:
          id: circleId
        insertion_order: null
        remote_table:
          name: circle_leader
          schema: public
  - name: members
    using:
      foreign_key_constraint_on:
        column: circleId
        table:
          name: circle_member
          schema: public
  - name: participants
    using:
      manual_configuration:
        column_mapping:
          id: circleId
        insertion_order: null
        remote_table:
          name: circle_participant_cache
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        _and:
          - _not:
              _exists:
                _table:
                  name: circle
                  schema: public
                _where:
                  _and:
                    - id:
                        _cne: id
                    - roleId:
                        _ceq: roleId
          - _or:
              - org:
                  members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - role:
                          _eq: Owner
              - org:
                  _and:
                    - protectGovernance:
                        _eq: false
                    - members:
                        _and:
                          - userId:
                              _eq: X-Hasura-User-Id
                          - _or:
                              - role:
                                  _eq: Admin
                              - role:
                                  _eq: Member
              - _and:
                  - role:
                      parentLink:
                        _eq: false
                  - parent:
                      leaders:
                        member:
                          userId:
                            _eq: X-Hasura-User-Id
              - _and:
                  - role:
                      parentLink:
                        _eq: true
                  - parent:
                      parent:
                        leaders:
                          member:
                            userId:
                              _eq: X-Hasura-User-Id
      columns:
        - archived
        - orgId
        - parentId
        - roleId
select_permissions:
  - role: public
    permission:
      columns:
        - archived
        - id
        - orgId
        - parentId
        - roleId
      filter:
        _and:
          - archived:
              _eq: false
          - org:
              shareOrg:
                _eq: true
  - role: user
    permission:
      columns:
        - archived
        - id
        - orgId
        - parentId
        - roleId
      filter: {}
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - archived
        - parentId
      filter:
        _or:
          - org:
              members:
                _and:
                  - userId:
                      _eq: X-Hasura-User-Id
                  - role:
                      _eq: Owner
          - org:
              _and:
                - protectGovernance:
                    _eq: false
                - members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - _or:
                          - role:
                              _eq: Admin
                          - role:
                              _eq: Member
          - _and:
              - role:
                  parentLink:
                    _eq: false
              - parent:
                  leaders:
                    member:
                      userId:
                        _eq: X-Hasura-User-Id
          - _and:
              - role:
                  parentLink:
                    _eq: true
              - parent:
                  parent:
                    leaders:
                      member:
                        userId:
                          _eq: X-Hasura-User-Id
      check:
        _or:
          - org:
              members:
                _and:
                  - userId:
                      _eq: X-Hasura-User-Id
                  - role:
                      _eq: Owner
          - org:
              _and:
                - protectGovernance:
                    _eq: false
                - members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - _or:
                          - role:
                              _eq: Admin
                          - role:
                              _eq: Member
          - _and:
              - role:
                  parentLink:
                    _eq: false
              - parent:
                  leaders:
                    member:
                      userId:
                        _eq: X-Hasura-User-Id
          - _and:
              - role:
                  parentLink:
                    _eq: true
              - parent:
                  parent:
                    leaders:
                      member:
                        userId:
                          _eq: X-Hasura-User-Id
event_triggers:
  - name: index-circle
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    webhook: '{{NHOST_FUNCTIONS_URL}}/routes/events/indexEntity'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
