table:
  name: meeting
  schema: public
object_relationships:
  - name: circle
    using:
      foreign_key_constraint_on: circleId
  - name: org
    using:
      foreign_key_constraint_on: orgId
  - name: recurring
    using:
      foreign_key_constraint_on: recurringId
array_relationships:
  - name: meeting_attendees
    using:
      foreign_key_constraint_on:
        column: meetingId
        table:
          name: meeting_attendee
          schema: public
  - name: steps
    using:
      foreign_key_constraint_on:
        column: meetingId
        table:
          name: meeting_step
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        _or:
          - circle:
              participants:
                member:
                  userId:
                    _eq: X-Hasura-User-Id
          - _and:
              - invitedReadonly:
                  _eq: false
              - meeting_attendees:
                  member:
                    userId:
                      _eq: X-Hasura-User-Id
          - _and:
              - private:
                  _eq: false
              - invitedReadonly:
                  _eq: false
              - org:
                  members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - _or:
                          - role:
                              _eq: Member
                          - role:
                              _eq: Admin
                          - role:
                              _eq: Owner
      columns:
        - circleId
        - endDate
        - invitedReadonly
        - orgId
        - private
        - recurringDate
        - recurringId
        - startDate
        - stepsConfig
        - title
        - videoConf
select_permissions:
  - role: user
    permission:
      columns:
        - archived
        - circleId
        - createdAt
        - currentStepId
        - endDate
        - ended
        - id
        - invitedReadonly
        - orgId
        - private
        - recurringDate
        - recurringId
        - startDate
        - stepsConfig
        - summary
        - title
        - videoConf
      filter:
        _or:
          - circle:
              participants:
                member:
                  userId:
                    _eq: X-Hasura-User-Id
          - meeting_attendees:
              member:
                userId:
                  _eq: X-Hasura-User-Id
          - _and:
              - private:
                  _eq: false
              - org:
                  members:
                    userId:
                      _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - archived
        - circleId
        - currentStepId
        - endDate
        - ended
        - invitedReadonly
        - private
        - startDate
        - stepsConfig
        - summary
        - title
        - videoConf
      filter:
        _or:
          - circle:
              participants:
                member:
                  userId:
                    _eq: X-Hasura-User-Id
          - _and:
              - invitedReadonly:
                  _eq: false
              - meeting_attendees:
                  member:
                    userId:
                      _eq: X-Hasura-User-Id
          - _and:
              - private:
                  _eq: false
              - invitedReadonly:
                  _eq: false
              - org:
                  members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - _or:
                          - role:
                              _eq: Member
                          - role:
                              _eq: Admin
                          - role:
                              _eq: Owner
      check:
        _or:
          - circle:
              participants:
                member:
                  userId:
                    _eq: X-Hasura-User-Id
          - _and:
              - invitedReadonly:
                  _eq: false
              - meeting_attendees:
                  member:
                    userId:
                      _eq: X-Hasura-User-Id
          - _and:
              - private:
                  _eq: false
              - invitedReadonly:
                  _eq: false
              - org:
                  members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - _or:
                          - role:
                              _eq: Member
                          - role:
                              _eq: Admin
                          - role:
                              _eq: Owner
event_triggers:
  - name: index-meeting
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - id
          - orgId
          - createdAt
          - startDate
          - endDate
          - ended
          - currentStepId
          - archived
          - circleId
          - videoConf
          - recurringId
          - recurringDate
          - summary
          - title
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    webhook: '{{NHOST_FUNCTIONS_URL}}/routes/events/indexEntity'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
