table:
  name: role
  schema: public
object_relationships:
  - name: org
    using:
      foreign_key_constraint_on: orgId
array_relationships:
  - name: circles
    using:
      foreign_key_constraint_on:
        column: roleId
        table:
          name: circle
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        _or:
          - org:
              members:
                _and:
                  - userId:
                      _eq: X-Hasura-User-Id
                  - role:
                      _eq: Owner
          - _and:
              - base:
                  _eq: false
              - org:
                  members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - _or:
                          - role:
                              _eq: Admin
                          - role:
                              _eq: Member
      columns:
        - accountabilities
        - archived
        - base
        - checklist
        - colorHue
        - defaultMinPerWeek
        - domain
        - indicators
        - name
        - notes
        - orgId
        - parentLink
        - purpose
        - singleMember
select_permissions:
  - role: public
    permission:
      columns:
        - archived
        - base
        - colorHue
        - id
        - name
        - orgId
        - parentLink
        - purpose
        - singleMember
      filter:
        _and:
          - archived:
              _eq: false
          - org:
              shareOrg:
                _eq: true
  - role: user
    permission:
      columns:
        - accountabilities
        - archived
        - base
        - checklist
        - colorHue
        - defaultMinPerWeek
        - domain
        - id
        - indicators
        - name
        - notes
        - orgId
        - parentLink
        - purpose
        - singleMember
      filter:
        org:
          members:
            userId:
              _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - accountabilities
        - archived
        - base
        - checklist
        - colorHue
        - defaultMinPerWeek
        - domain
        - indicators
        - name
        - notes
        - parentLink
        - purpose
        - singleMember
      filter:
        _or:
          - org:
              members:
                _and:
                  - userId:
                      _eq: X-Hasura-User-Id
                  - role:
                      _eq: Owner
          - _and:
              - base:
                  _eq: false
              - _or:
                  - org:
                      _and:
                        - protectGovernance:
                            _eq: false
                        - members:
                            _and:
                              - userId:
                                  _eq: X-Hasura-User-Id
                              - _or:
                                  - role:
                                      _eq: Admin
                                  - role:
                                      _eq: Member
                  - _and:
                      - parentLink:
                          _eq: false
                      - circles:
                          parent:
                            leaders:
                              member:
                                userId:
                                  _eq: X-Hasura-User-Id
                  - _and:
                      - parentLink:
                          _eq: true
                      - circles:
                          parent:
                            parent:
                              leaders:
                                member:
                                  userId:
                                    _eq: X-Hasura-User-Id
      check:
        _or:
          - org:
              members:
                _and:
                  - userId:
                      _eq: X-Hasura-User-Id
                  - role:
                      _eq: Owner
          - _and:
              - base:
                  _eq: false
              - _or:
                  - org:
                      _and:
                        - protectGovernance:
                            _eq: false
                        - members:
                            _and:
                              - userId:
                                  _eq: X-Hasura-User-Id
                              - _or:
                                  - role:
                                      _eq: Admin
                                  - role:
                                      _eq: Member
                  - _and:
                      - parentLink:
                          _eq: false
                      - circles:
                          parent:
                            leaders:
                              member:
                                userId:
                                  _eq: X-Hasura-User-Id
                  - _and:
                      - parentLink:
                          _eq: true
                      - circles:
                          parent:
                            parent:
                              leaders:
                                member:
                                  userId:
                                    _eq: X-Hasura-User-Id
event_triggers:
  - name: index-role
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    webhook: '{{BACKEND_URL}}/trigger'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
