table:
  name: thread
  schema: public
object_relationships:
  - name: circle
    using:
      foreign_key_constraint_on: circleId
  - name: initiatorMember
    using:
      foreign_key_constraint_on: initiatorMemberId
  - name: org
    using:
      foreign_key_constraint_on: orgId
array_relationships:
  - name: activities
    using:
      manual_configuration:
        column_mapping:
          id: threadId
        insertion_order: null
        remote_table:
          name: thread_activity
          schema: public
  - name: extra_members
    using:
      foreign_key_constraint_on:
        column: threadId
        table:
          name: thread_extra_member
          schema: public
  - name: logs
    using:
      foreign_key_constraint_on:
        column: threadId
        table:
          name: log
          schema: public
  - name: member_status
    using:
      foreign_key_constraint_on:
        column: threadId
        table:
          name: thread_member_status
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        _or:
          - circle:
              participants:
                member:
                  userId:
                    _eq: X-Hasura-User-Id
          - extra_members:
              member:
                userId:
                  _eq: X-Hasura-User-Id
          - _and:
              - private:
                  _eq: false
              - org:
                  members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - _or:
                          - role:
                              _eq: Member
                          - role:
                              _eq: Admin
                          - role:
                              _eq: Owner
      columns:
        - archived
        - circleId
        - initiatorMemberId
        - orgId
        - private
        - status
        - title
select_permissions:
  - role: user
    permission:
      columns:
        - archived
        - circleId
        - createdAt
        - id
        - initiatorMemberId
        - orgId
        - private
        - status
        - title
      filter:
        _or:
          - circle:
              participants:
                member:
                  userId:
                    _eq: X-Hasura-User-Id
          - extra_members:
              member:
                userId:
                  _eq: X-Hasura-User-Id
          - _and:
              - private:
                  _eq: false
              - org:
                  members:
                    userId:
                      _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - archived
        - circleId
        - private
        - status
        - title
      filter:
        _or:
          - circle:
              participants:
                member:
                  userId:
                    _eq: X-Hasura-User-Id
          - extra_members:
              member:
                userId:
                  _eq: X-Hasura-User-Id
          - _and:
              - private:
                  _eq: false
              - org:
                  members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - _or:
                          - role:
                              _eq: Member
                          - role:
                              _eq: Admin
                          - role:
                              _eq: Owner
      check:
        _or:
          - circle:
              participants:
                member:
                  userId:
                    _eq: X-Hasura-User-Id
          - extra_members:
              member:
                userId:
                  _eq: X-Hasura-User-Id
          - _and:
              - private:
                  _eq: false
              - org:
                  members:
                    _and:
                      - userId:
                          _eq: X-Hasura-User-Id
                      - _or:
                          - role:
                              _eq: Member
                          - role:
                              _eq: Admin
                          - role:
                              _eq: Owner
event_triggers:
  - name: index-thread
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    webhook: '{{BACKEND_URL}}/trigger'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
