table:
  name: meeting
  schema: public
object_relationships:
  - name: circle
    using:
      foreign_key_constraint_on: circleId
  - name: org
    using:
      foreign_key_constraint_on: orgId
  - name: recurring
    using:
      foreign_key_constraint_on: recurringId
array_relationships:
  - name: steps
    using:
      foreign_key_constraint_on:
        column: meetingId
        table:
          name: meeting_step
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        org:
          members:
            _and:
              - userId:
                  _eq: X-Hasura-User-Id
              - _or:
                  - role:
                      _eq: Member
                  - role:
                      _eq: Admin
                  - role:
                      _eq: Owner
      columns:
        - attendees
        - circleId
        - endDate
        - orgId
        - participantsMembersIds
        - participantsScope
        - recurringDate
        - recurringId
        - startDate
        - stepsConfig
        - title
        - videoConf
select_permissions:
  - role: user
    permission:
      columns:
        - archived
        - attendees
        - circleId
        - createdAt
        - currentStepId
        - endDate
        - ended
        - id
        - orgId
        - participantsMembersIds
        - participantsScope
        - recurringDate
        - recurringId
        - startDate
        - stepsConfig
        - title
        - videoConf
      filter:
        org:
          members:
            userId:
              _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - archived
        - attendees
        - circleId
        - currentStepId
        - endDate
        - ended
        - participantsMembersIds
        - participantsScope
        - startDate
        - stepsConfig
        - title
        - videoConf
      filter:
        org:
          members:
            _and:
              - userId:
                  _eq: X-Hasura-User-Id
              - _or:
                  - role:
                      _eq: Member
                  - role:
                      _eq: Admin
                  - role:
                      _eq: Owner
      check: {}
event_triggers:
  - name: index-meeting
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    webhook: '{{NHOST_BACKEND_URL}}/v1/functions/routes/indexEntity'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: send-meeting-invited-notification
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - circleId
          - participantsMembersIds
          - participantsScope
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{NHOST_BACKEND_URL}}/v1/functions/routes/events/sendMeetingInvitedNotification'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
