table:
  name: role
  schema: public
object_relationships:
  - name: org
    using:
      foreign_key_constraint_on: orgId
array_relationships:
  - name: circles
    using:
      foreign_key_constraint_on:
        column: roleId
        table:
          name: circle
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        org:
          members:
            _and:
              - userId:
                  _eq: X-Hasura-User-Id
              - _or:
                  - role:
                      _eq: Member
                  - role:
                      _eq: Admin
                  - role:
                      _eq: Owner
      columns:
        - accountabilities
        - archived
        - base
        - checklist
        - colorHue
        - defaultMinPerWeek
        - domain
        - indicators
        - link
        - name
        - notes
        - orgId
        - purpose
        - singleMember
select_permissions:
  - role: public
    permission:
      columns:
        - archived
        - base
        - colorHue
        - id
        - link
        - name
        - orgId
        - purpose
        - singleMember
      filter:
        _and:
          - archived:
              _eq: false
          - org:
              shareOrg:
                _eq: true
  - role: user
    permission:
      columns:
        - accountabilities
        - archived
        - base
        - checklist
        - colorHue
        - defaultMinPerWeek
        - domain
        - id
        - indicators
        - link
        - name
        - notes
        - orgId
        - purpose
        - singleMember
      filter:
        org:
          members:
            userId:
              _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - accountabilities
        - archived
        - base
        - checklist
        - colorHue
        - defaultMinPerWeek
        - domain
        - indicators
        - link
        - name
        - notes
        - purpose
        - singleMember
      filter:
        org:
          members:
            _and:
              - userId:
                  _eq: X-Hasura-User-Id
              - _or:
                  - role:
                      _eq: Member
                  - role:
                      _eq: Admin
                  - role:
                      _eq: Owner
      check: {}
event_triggers:
  - name: index-role
    definition:
      enable_manual: false
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    webhook: '{{NHOST_FUNCTIONS_URL}}/routes/events/indexEntity'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
