table:
  name: task
  schema: public
object_relationships:
  - name: circle
    using:
      foreign_key_constraint_on: circleId
  - name: member
    using:
      foreign_key_constraint_on: memberId
  - name: org
    using:
      foreign_key_constraint_on: orgId
insert_permissions:
  - role: user
    permission:
      check:
        org:
          members:
            _and:
              - userId:
                  _eq: X-Hasura-User-Id
              - _or:
                  - role:
                      _eq: Member
                  - role:
                      _eq: Admin
                  - role:
                      _eq: Owner
      columns:
        - archived
        - circleId
        - description
        - dueDate
        - memberId
        - orgId
        - status
        - title
select_permissions:
  - role: user
    permission:
      columns:
        - archived
        - description
        - status
        - title
        - createdAt
        - dueDate
        - circleId
        - id
        - memberId
        - orgId
      filter:
        org:
          members:
            userId:
              _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - archived
        - circleId
        - description
        - dueDate
        - memberId
        - status
        - title
      filter:
        org:
          members:
            _and:
              - userId:
                  _eq: X-Hasura-User-Id
              - _or:
                  - role:
                      _eq: Member
                  - role:
                      _eq: Admin
                  - role:
                      _eq: Owner
      check: {}
event_triggers:
  - name: index-task
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    webhook: '{{NHOST_BACKEND_URL}}/v1/functions/routes/indexEntity'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: send-task-assigned-notification
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - memberId
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{NHOST_BACKEND_URL}}/v1/functions/routes/events/sendTaskAssignedNotification'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
