table:
  name: thread_activity
  schema: public
object_relationships:
  - name: refDecision
    using:
      manual_configuration:
        column_mapping:
          refDecisionId: id
        insertion_order: null
        remote_table:
          name: decision
          schema: public
  - name: refMeeting
    using:
      manual_configuration:
        column_mapping:
          refMeetingId: id
        insertion_order: null
        remote_table:
          name: meeting
          schema: public
  - name: refTask
    using:
      manual_configuration:
        column_mapping:
          refTaskId: id
        insertion_order: null
        remote_table:
          name: task
          schema: public
  - name: refThread
    using:
      manual_configuration:
        column_mapping:
          refThreadId: id
        insertion_order: null
        remote_table:
          name: thread
          schema: public
  - name: thread
    using:
      foreign_key_constraint_on: threadId
  - name: user
    using:
      foreign_key_constraint_on: userId
insert_permissions:
  - role: user
    permission:
      check:
        thread:
          org:
            members:
              _and:
                - userId:
                    _eq: X-Hasura-User-Id
                - _or:
                    - role:
                        _eq: Member
                    - role:
                        _eq: Admin
                    - role:
                        _eq: Owner
      set:
        userId: x-hasura-User-Id
      columns:
        - data
        - refDecisionId
        - refMeetingId
        - refTaskId
        - refThreadId
        - threadId
        - type
select_permissions:
  - role: user
    permission:
      columns:
        - createdAt
        - data
        - id
        - refDecisionId
        - refMeetingId
        - refTaskId
        - refThreadId
        - threadId
        - type
        - userId
      filter:
        thread:
          org:
            members:
              userId:
                _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - data
      filter:
        _or:
          - userId:
              _eq: X-Hasura-User-Id
          - _and:
              - type:
                  _eq: MeetingNote
              - thread:
                  org:
                    members:
                      _and:
                        - userId:
                            _eq: X-Hasura-User-Id
                        - _or:
                            - role:
                                _eq: Member
                            - role:
                                _eq: Admin
      check: {}
delete_permissions:
  - role: user
    permission:
      filter:
        _or:
          - thread:
              org:
                members:
                  _and:
                    - userId:
                        _eq: X-Hasura-User-Id
                    - _or:
                        - role:
                            _eq: Member
                        - role:
                            _eq: Admin
          - userId:
              _eq: X-Hasura-User-Id
event_triggers:
  - name: send-thread-activity-notification
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{NHOST_BACKEND_URL}}/v1/functions/routes/events/sendThreadActivityNotification'
    headers:
      - name: x-nhost-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
