-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."circle_member" add column "archived" boolean
--  not null default 'false';
