import { RoleEntry } from '@shared/role'

export const roles: RoleEntry[] = [
  {
    id: 'role-super',
    orgId: 'org-1',
    archived: false,
    base: false,
    name: 'SuperOrga',
    purpose: '',
    domain: '',
    accountabilities: '',
    notes: '',
    singleMember: false,
    link: false,
    defaultMinPerWeek: null,
  },
  {
    id: 'role-agence',
    orgId: 'org-1',
    archived: false,
    base: false,
    name: 'Agence',
    purpose: '',
    domain: '',
    accountabilities: '',
    notes: '',
    singleMember: false,
    link: false,
    defaultMinPerWeek: null,
  },
  {
    id: 'role-studio',
    orgId: 'org-1',
    archived: false,
    base: false,
    name: 'Studio',
    purpose: '',
    domain: '',
    accountabilities: '',
    notes: '',
    singleMember: false,
    link: false,
    defaultMinPerWeek: null,
  },
  {
    id: 'role-am',
    orgId: 'org-1',
    archived: false,
    base: false,
    name: 'Account Managers',
    purpose: '',
    domain: '',
    accountabilities: '',
    notes: '',
    singleMember: false,
    link: false,
    defaultMinPerWeek: null,
  },
  {
    id: 'role-dev',
    orgId: 'org-1',
    archived: false,
    base: false,
    name: 'Développeurs',
    purpose: '',
    domain: '',
    accountabilities: '',
    notes: '',
    singleMember: false,
    link: false,
    defaultMinPerWeek: null,
  },
  {
    id: 'role-leader',
    orgId: 'org-1',
    archived: false,
    base: true,
    name: 'Leader',
    purpose: '',
    domain: '',
    accountabilities: '',
    notes: '',
    singleMember: true,
    link: true,
    defaultMinPerWeek: null,
  },
  {
    id: 'role-facilitator',
    orgId: 'org-1',
    archived: false,
    base: true,
    name: 'Facilitateur',
    purpose: '',
    domain: '',
    accountabilities: '',
    notes: '',
    singleMember: true,
    link: false,
    defaultMinPerWeek: null,
  },
]
