-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."meeting_attendee" add column "startNotified" boolean
--  not null default 'false';
