-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."thread_poll_answer" add column "choicesPoints" json
--  not null;
