scalar strings
scalar attendee
scalar meeting_step_config
scalar meeting_step_data
scalar videoconf
scalar thread_activity_data
scalar log_display
scalar log_changes

extend type meeting {
  participantsMembersIds: [uuid!]!
  attendees: [attendee!]
  stepsConfig: [meeting_step_config!]!
  videoConf: videoconf
}

extend type meeting_template {
  stepsConfig: [meeting_step_config!]!
}

extend type meeting_step {
  data: meeting_step_data!
}

extend type meeting_recurring {
  participantsMembersIds: [uuid!]!
}

extend type task {
  tasksIds: [uuid!]!
}

extend type thread {
  participantsMembersIds: [uuid!]!
}

extend type thread_poll_answer {
  choicesPoints: [Int!]!
}

extend type log {
  display: log_display!
  changes: log_changes!
}
