scalar attendee
scalar meeting_step_config
scalar meeting_step_data
scalar videoconf
scalar log_display
scalar log_changes

type meeting {
  participantsMembersIds: [uuid!]!
  attendees: [attendee!]
  stepsConfig: [meeting_step_config!]!
  videoConf: videoconf
}

type meeting_template {
  stepsConfig: [meeting_step_config!]!
}

type meeting_step {
  data: meeting_step_data!
}

type meeting_recurring {
  participantsMembersIds: [uuid!]!
}

type task_view {
  tasksIds: [uuid!]!
}

type thread {
  participantsMembersIds: [uuid!]!
}

type thread_poll_answer {
  choicesPoints: [Int!]!
}

type log {
  display: log_display!
  changes: log_changes!
}
