query getLastMeetingSteps($recurringId: uuid!, $recurringDate: timestamptz!) {
  meeting(
    where: {
      recurringId: { _eq: $recurringId }
      recurringDate: { _lt: $recurringDate }
      archived: { _eq: false }
    }
    order_by: { createdAt: desc }
    limit: 1
  ) {
    steps {
      ...MeetingStep
    }
  }
}

subscription meeting($id: uuid!) {
  meeting_by_pk(id: $id) {
    ...Meeting
    steps {
      ...MeetingStep
    }
  }
}

subscription meetingsByDates(
  $orgId: uuid!
  $fromDate: timestamptz!
  $toDate: timestamptz!
) {
  org_by_pk(id: $orgId) {
    meetings(
      where: {
        startDate: { _gte: $fromDate, _lt: $toDate }
        archived: { _eq: false }
      }
    ) {
      ...MeetingSummary
    }
    meetings_recurring {
      ...MeetingRecurring
      meetings(where: { recurringDate: { _gte: $fromDate, _lt: $toDate } }) {
        id
        recurringDate
      }
    }
  }
}

subscription nextMeetings {
  meeting(
    where: {
      archived: { _eq: false }
      endDate: { _gt: "now()" } # Include meetings that are still in progress
    }
    order_by: { startDate: asc }
  ) {
    ...MeetingSummary
  }
}

subscription circleMeetings($circleId: uuid!) {
  meeting(
    where: { circleId: { _eq: $circleId }, archived: { _eq: false } }
    order_by: { startDate: desc }
  ) {
    ...MeetingSummary
  }
}

mutation createMeeting($values: meeting_insert_input!) {
  insert_meeting_one(object: $values) {
    ...Meeting
  }
}

mutation updateMeeting($id: uuid!, $values: meeting_set_input!) {
  update_meeting_by_pk(pk_columns: { id: $id }, _set: $values) {
    ...Meeting
  }
}

mutation archiveMeeting($id: uuid!) {
  update_meeting_by_pk(pk_columns: { id: $id }, _set: { archived: true }) {
    id
  }
}
