query getOrg($id: uuid!) {
  org_by_pk(id: $id) {
    ...Org
  }
}

subscription orgs($userId: uuid!) {
  member(
    where: {
      userId: { _eq: $userId }
      archived: { _eq: false }
      org: { archived: { _eq: false } }
    }
  ) {
    org {
      ...Org
    }
  }
}

subscription org($id: uuid!) {
  org_by_pk(id: $id) {
    ...OrgFullLight
  }
}

subscription orgBySlug($slug: String!) {
  org(where: { slug: { _eq: $slug } }, limit: 1) {
    ...OrgFullLight
  }
}

mutation updateOrg($id: uuid!, $values: org_set_input!) {
  update_org_by_pk(pk_columns: { id: $id }, _set: $values) {
    id
  }
}
