query getTask($id: uuid!) {
  task_by_pk(id: $id) {
    ...Task
  }
}

subscription task($id: uuid!) {
  task_by_pk(id: $id) {
    ...Task
  }
}

subscription tasks($filters: [task_bool_exp!]) {
  task(where: { _and: $filters }) {
    ...Task
  }
}

mutation createTask($values: task_insert_input!) {
  insert_task_one(object: $values) {
    ...Task
  }
}

mutation updateTask($id: uuid!, $values: task_set_input!) {
  update_task_by_pk(pk_columns: { id: $id }, _set: $values) {
    ...Task
  }
}

mutation archiveTask($id: uuid!) {
  update_task_by_pk(pk_columns: { id: $id }, _set: { archived: true }) {
    id
  }
}
