-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."meeting_recurring" add column "scope" json
--  not null default '[]';
