-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE INDEX "meeting_currentStepId_key" ON meeting ("currentStepId") WHERE "currentStepId" IS NOT NULL;
