query getLastThreadActivity($threadId: uuid!) {
  thread_activity(
    where: { threadId: { _eq: $threadId } }
    order_by: { createdAt: desc }
    limit: 1
  ) {
    ...ThreadActivity
  }
}

subscription threadActivity($id: uuid!) {
  thread_activity_by_pk(id: $id) {
    ...ThreadActivity
  }
}

subscription threadActivities($threadId: uuid!) {
  thread_activity(
    where: { threadId: { _eq: $threadId } }
    order_by: { createdAt: asc }
  ) {
    ...ThreadActivity
  }
}

mutation createThreadActivity($values: thread_activity_insert_input!) {
  insert_thread_activity_one(object: $values) {
    ...ThreadActivity
  }
}

mutation updateThreadActivity($id: uuid!, $values: thread_activity_set_input!) {
  update_thread_activity_by_pk(pk_columns: { id: $id }, _set: $values) {
    ...ThreadActivity
  }
}

mutation deleteThreadActivity($id: uuid!) {
  delete_thread_activity_by_pk(id: $id) {
    id
  }
}
