-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE member_scope (
--   value text PRIMARY KEY,
--   comment text
-- );
--
-- INSERT INTO member_scope (value, comment) VALUES
-- ('Organization', 'All members of the organization'),
-- ('CircleLeaders', 'All Leaders of Roles and sub-Circles in Circle'),
-- ('CircleMembers', 'All members in Circle and sub-Circles'),
-- ('None', 'None (select members manually)');
