-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."meeting" add column "private" boolean
--  not null default 'false';
