fragment Meeting on meeting {
  id
  orgId
  circleId
  participantsScope
  participantsMembersIds
  createdAt
  startDate
  endDate
  ended
  title
  attendees
  stepsConfig
  currentStepId
  archived
  videoConf
  recurringId
  recurringDate
  steps {
    notes
    type
    stepConfigId
    id
    meetingId
    data
  }
}

fragment MeetingSummary on meeting {
  id
  orgId
  circleId
  participantsScope
  participantsMembersIds
  startDate
  endDate
  ended
  title
  currentStepId
}
