fragment Member on member {
  id
  orgId
  archived
  name
  description
  pictureFileId
  picture
  userId
  inviteEmail
  inviteDate
  workedMinPerWeek
  role
  meetingId
}

fragment MemberSummary on member {
  id
  userId
  name
  picture
}
