fragment Org on org {
  id
  name
  archived
  createdAt
  defaultWorkedMinPerWeek
  slug
}

fragment OrgFull on org {
  ...Org
  circles(where: { archived: { _eq: false } }) {
    ...CircleFull
  }
  roles(where: { archived: { _eq: false } }) {
    ...Role
  }
  members(where: { archived: { _eq: false } }) {
    ...Member
  }
}
