fragment Role on role {
  id
  orgId
  archived
  base
  name
  purpose
  domain
  accountabilities
  checklist
  indicators
  notes
  singleMember
  autoCreate
  link
  defaultMinPerWeek
  colorHue
}

fragment RoleSummary on role {
  id
  name
  link
  singleMember
  colorHue
}
