fragment Task on task {
  id
  orgId
  circleId
  memberId
  title
  description
  archived
  createdAt
  dueDate
  status
}

fragment TaskNotificationData on task {
  ...Task
  org {
    ...Org
    members(where: { id: { _eq: $memberId } }) {
      id
      name
      user {
        id
        email
        locale
      }
    }
  }
  circle {
    id
    role {
      name
    }
  }
}
