spectaql:
  targetDir: dist
  logoFile: ../webapp/public/logo.png
  logoHeightPx: 18
  faviconFile: ../webapp/src/images/icon.svg

introspection:
  url: https://local.hasura.nhost.run/v1/graphql
  headers:
    x-hasura-admin-secret: nhost-admin-secret
  metadataFile: metadata.js

info:
  title: API Documentation - Rolebase
  description: Rolebase GraphQL API for developers
  version: 1.0.0
  termsOfService: 'https://www.rolebase.io/conditions-generales-de-vente'
  contact:
    name: Rolebase Support
    email: contact@rolebase.io
    url: https://www.rolebase.io/contact
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

  x-introItems:
    - title: A silly link to our website!
      url: http://yoursite.com
    - title: Important thing 1
      description: Some important stuff we wanted you to know. Supports `markdown`
