---
name: 'Test and Release'
on:
  workflow_call:
    inputs:
      IMAGE:
        type: string
        required: true
      SERVICE_ID:
        type: string
        required: true
    secrets:
      PAT:
        required: true

env:
  NODE_VERSION: 20

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm install
          npm run test

  # Deploy backend
  deploy:
    needs: [test]
    uses: ./.github/workflows/build-and-release-nhost-run.yaml
    with:
      IMAGE: ${{ inputs.IMAGE }}
      SERVICE_ID: ${{ inputs.SERVICE_ID }}
      DOCKER_FILE: ./packages/backend/Dockerfile
    secrets:
      PAT: ${{ secrets.PAT }}
