fragment MeetingRecurring on meeting_recurring {
  id
  orgId
  circleId
  circle {
    role {
      name
      colorHue
    }
  }
  participantsScope
  participantsMembersIds
  templateId
  template {
    title
    stepsConfig
  }
  rrule
  duration
  videoConf
  createdAt
}
