fragment Role on role {
  id
  orgId
  archived
  base
  name
  purpose
  domain
  accountabilities
  checklist
  indicators
  notes
  singleMember
  parentLink
  defaultMinPerWeek
  colorHue
}

fragment RoleSummary on role {
  id
  base
  name
  singleMember
  parentLink
  defaultMinPerWeek
  colorHue
}
